CREATEDATABASE`upload`;

CREATE TABLE IF NOT EXISTS `gravator` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`path` varchar(200) NOT NULL,
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=Latin1 AUTO_INCREMENT=1 ;